# Generated by Django 5.1.3 on 2024-12-19 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Lesson",
            new_name="Video",
        ),
    ]
