# Generated by Django 5.1.3 on 2024-12-20 20:51

import cloudinary_storage.storage
import videos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0002_rename_lesson_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="poster",
            field=models.ImageField(
                blank=True,
                max_length=1000,
                null=True,
                storage=cloudinary_storage.storage.MediaCloudinaryStorage(),
                upload_to=videos.models.photo_path,
            ),
        ),
    ]
