# Generated by Django 5.1.3 on 2024-12-02 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="token",
            field=models.CharField(
                default=1, editable=False, max_length=20, unique=True
            ),
            preserve_default=False,
        ),
    ]
