# Generated by Django 5.1.3 on 2024-12-09 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="name_en",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="equipment",
            name="name_uk",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
