# Generated by Django 5.1.3 on 2024-11-25 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="model_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="type",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
