# Generated by Django 5.1.3 on 2024-12-01 17:30

import cloudinary_storage.storage
import equipment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment",
            name="model",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=cloudinary_storage.storage.MediaCloudinaryStorage(),
                upload_to=equipment.models.photo_path,
            ),
        ),
    ]
