# Generated by Django 5.1.3 on 2024-11-28 11:42

import equipment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0002_alter_equipment_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="equipment",
            name="description",
        ),
        migrations.RemoveField(
            model_name="equipment",
            name="rental_price",
        ),
        migrations.AddField(
            model_name="equipment",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=equipment.models.image_path
            ),
        ),
    ]
