# Generated by Django 5.1.3 on 2024-11-28 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0003_remove_equipment_description_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="equipment",
            old_name="model_name",
            new_name="model",
        ),
        migrations.RemoveField(
            model_name="equipment",
            name="type",
        ),
    ]
