# Generated by Django 5.1.3 on 2024-12-14 18:17

import cloudinary_storage.storage
import services.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("title_en", models.CharField(max_length=250, null=True)),
                ("title_uk", models.CharField(max_length=250, null=True)),
                ("details_block1", models.TextField(blank=True, null=True)),
                ("details_block1_en", models.TextField(blank=True, null=True)),
                ("details_block1_uk", models.TextField(blank=True, null=True)),
                ("details_block2", models.TextField(blank=True, null=True)),
                ("details_block2_en", models.TextField(blank=True, null=True)),
                ("details_block2_uk", models.TextField(blank=True, null=True)),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        storage=cloudinary_storage.storage.MediaCloudinaryStorage(),
                        upload_to=services.models.photo_path,
                    ),
                ),
            ],
        ),
    ]
