# Generated by Django 5.1.3 on 2024-12-23 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="details_block3",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="hourly",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="price",
            field=models.DecimalField(decimal_places=2, default=True, max_digits=8),
            preserve_default=False,
        ),
    ]
