# Generated by Django 5.1.3 on 2024-12-23 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_service_details_block3_service_hourly_service_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="details_block3_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="details_block3_uk",
            field=models.TextField(blank=True, null=True),
        ),
    ]
