# Generated by Django 5.1.3 on 2024-12-14 18:17

import cloudinary_storage.storage
import songs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("title_en", models.CharField(max_length=100, null=True)),
                ("title_uk", models.CharField(max_length=100, null=True)),
                ("artist", models.CharField(max_length=100)),
                ("artist_en", models.CharField(max_length=100, null=True)),
                ("artist_uk", models.CharField(max_length=100, null=True)),
                (
                    "audio_file",
                    models.FileField(
                        max_length=1000, upload_to=songs.models.audio_path
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        storage=cloudinary_storage.storage.MediaCloudinaryStorage(),
                        upload_to=songs.models.photo_path,
                    ),
                ),
                ("top", models.BooleanField(default=False)),
            ],
        ),
    ]
