# Generated by Django 5.1.3 on 2024-12-05 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("songs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="top",
            field=models.BooleanField(default=False),
        ),
    ]
