# Generated by Django 5.1.3 on 2024-12-09 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("songs", "0002_song_top"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="artist_en",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="song",
            name="artist_uk",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="song",
            name="title_en",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="song",
            name="title_uk",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
