# Generated by Django 5.1.3 on 2024-12-09 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="message_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="message_uk",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="name_en",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="name_uk",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="status_en",
            field=models.CharField(
                choices=[
                    ("not_started", "Not Started"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                ],
                default="not_started",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="status_uk",
            field=models.CharField(
                choices=[
                    ("not_started", "Not Started"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                ],
                default="not_started",
                max_length=20,
                null=True,
            ),
        ),
    ]
