# Generated by Django 5.1.3 on 2025-01-13 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_alter_notification_phone_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="message_en",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="message_uk",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="name_en",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="name_uk",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="status_en",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="status_uk",
        ),
    ]
