# Generated by Django 5.1.3 on 2024-12-02 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_chat"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="notify_allowed",
            field=models.BooleanField(default=True),
        ),
    ]
