# Generated by Django 5.1.3 on 2024-11-30 18:21

import cloudinary_storage.storage
import lessons.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description_block1", models.TextField(blank=True, null=True)),
                ("description_block2", models.TextField(blank=True, null=True)),
                (
                    "video_file",
                    models.FileField(
                        storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(),
                        upload_to=lessons.models.video_path,
                    ),
                ),
            ],
        ),
    ]
