# Generated by Django 5.1.3 on 2024-11-28 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="video_file",
            field=models.FileField(upload_to="video_path"),
        ),
    ]
