# Generated by Django 5.1.3 on 2024-12-09 22:06

import cloudinary_storage.storage
import lessons.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="description_block1_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lesson",
            name="description_block1_uk",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lesson",
            name="description_block2_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lesson",
            name="description_block2_uk",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lesson",
            name="title_en",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="lesson",
            name="title_uk",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="video_file",
            field=models.FileField(
                blank=True,
                max_length=1000,
                null=True,
                storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(),
                upload_to=lessons.models.video_path,
            ),
        ),
    ]
